
{{ if .Values.nats.enabled }}
---
apiVersion: eevee.bot/v1alpha1
kind: NatsCluster
metadata:
  name: {{ include "charts.fullname" . }}-nats-cluster
  namespace: {{ .Values.botNamespace | default "eevee-bot" }}
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  config:
    cluster:
      enabled: true
      port: 6222
      replicas: 3
    gateway:
      enabled: false
    jetstream:
      enabled: true
      {{ .Values.nats.jetstream | toYaml | nindent 6 }}
    leafnodes:
      enabled: false
    merge:
      authorization:
        token: << $TOKEN >>
    monitor:
      enabled: true
      port: 8222
    mqtt:
      enabled: false
    nats:
      port: 4222
    patch: []
    profiling:
      enabled: false
      port: 65432
    resolver:
      enabled: false
    websocket:
      enabled: false
  container:
    env:
      GOMEMLIMIT: 3.5GiB
      TOKEN:
        valueFrom:
          secretKeyRef:
            key: token
            name: {{ .Values.natsAuthSecret }}
    merge:
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 4Gi
  namespaceOverride: {{ .Values.botNamespace }}
  natsBox:
    enabled: false
  podDisruptionBudget:
    enabled: true
  promExporter:
    enabled: {{ .Values.metrics | default false}}
    podMonitor:
      enabled: {{ .Values.metrics | default false }}
  reloader:
    enabled: true
  service:
    enabled: true
    ports:
      cluster:
        enabled: true
      gateway:
        enabled: true
      leafnodes:
        enabled: true
      monitor:
        enabled: true
      mqtt:
        enabled: true
      nats:
        enabled: true
      profiling:
        enabled: true
      websocket:
        enabled: true
  serviceAccount:
    enabled: true

{{ end }}
