{{ if gt (len .Values.connectors.irc) 0 }}
{{ $global := .Values.global }}
{{ range .Values.connectors.irc }}
{{ $spec := merge $global . }}
---
apiVersion: eevee.bot/v1alpha1
kind: ConnectorIrc
metadata:
  name: {{ include "eevee-bot.fullname" $ }}-{{ .name }}-connector-irc
  namespace: {{ include "eevee-bot.botNamespace" $ }}
  labels:
  {{- include "eevee-bot.labels" $ | nindent 4 }}
spec:
  {{- $spec | toYaml | nindent 2 }}
{{ end }}
{{ end }}
