{{ if .Values.nats.enabled }}
---
apiVersion: eevee.bot/v1alpha1
kind: NatsCluster
metadata:
  name: {{ include "eevee-bot.fullname" . }}-nats-cluster
  namespace: {{ include "eevee-bot.botNamespace" $ }}
  labels:
  {{- include "eevee-bot.labels" . | nindent 4 }}
spec:
  config:
    cluster:
      enabled: true
      port: 6222
      replicas: {{ .Values.nats.replicas }}
    gateway:
      enabled: false
    leafnodes:
      enabled: false
    merge:
      authorization:
        token: << {{ `$TOKEN` }} >>
    monitor:
      enabled: true
      port: 8222
    mqtt:
      enabled: false
    nats:
      port: 4222
    patch: []
    profiling:
      enabled: false
      port: 65432
    resolver:
      enabled: false
    websocket:
      enabled: false
  container:
    env:
      TOKEN:
        valueFrom:
          secretKeyRef:
            key: token
            name: {{ .Values.global.natsAuthSecret }}
    merge:
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 4Gi
  namespaceOverride: {{ include "eevee-bot.botNamespace" $ }}
  natsBox:
    enabled: false
  podDisruptionBudget:
    enabled: true
  promExporter:
    enabled: {{ .Values.global.metrics }}
    podMonitor:
      enabled: {{ .Values.global.metrics }}
  reloader:
    enabled: true
  service:
    enabled: true
    name: nats
    ports:
      cluster:
        enabled: true
      gateway:
        enabled: true
      leafnodes:
        enabled: true
      monitor:
        enabled: true
      mqtt:
        enabled: true
      nats:
        enabled: true
      profiling:
        enabled: true
      websocket:
        enabled: true
  serviceAccount:
    enabled: true

{{ end }}
