{{ if .Values.toolbox.enabled }}
{{ $spec := merge .Values.global .Values.toolbox.spec }}
---
apiVersion: eevee.bot/v1alpha1
kind: Toolbox
metadata:
  name: {{ include "eevee-bot.fullname" $ }}-toolbox
  namespace: {{ include "eevee-bot.botNamespace" $ }}
  labels:
  {{- include "eevee-bot.labels" . | nindent 4 }}
spec:
  {{- $spec | toYaml | nindent 2 }}
{{ end }}
