{{ if .Values.toolbox.enabled }}
---
apiVersion: eevee.bot/v1alpha1
kind: Toolbox
metadata:
  name: {{ include "eevee-bot.fullname" $ }}-toolbox
  namespace: {{ include "eevee-bot.botNamespace" $ }}
  labels:
  {{- include "eevee-bot.labels" . | nindent 4 }}
spec:
  {{- merge .Values.all .Values.toolbox.spec | toYaml | nindent 2 }}
{{ end }}
