{{ if gt (len .Values.connectors.irc ) 0 }}
{{ range .Values.connectors.irc }}
---
apiVersion: eevee.bot/v1alpha1
kind: ConnectorIrc
metadata:
  name: {{ include "eevee-bot.fullname" $ }}-{{ .name }}-connector-irc
  namespace: {{ include "eevee-bot.botNamespace" $ }}
  labels:
  {{- include "eevee-bot.labels" $ | nindent 4 }}
spec:
  {{- merge .Values.global .spec | toYaml | nindent 2 }}
{{ end }}
{{ end }}
