---
# eevee Helm values

fullnameOverride: false
nameOverride: false

# Namespace for the operator
operatorNamespace: eevee-system

# Deploy the eevee-bot operator
operator:
  enabled: true
  replicas: 1
