---
# eevee Helm values

nameOverride: false
fullnameOverride: false

# Namespace for the operator
operatorNamespace: eevee-system

# Deploy the eevee-bot operator
operator:
  enabled: true
  replicas: 1
