apiVersion: v2
name: eevee
description: A Helm chart for eevee.bot ecosystem deployment
type: application
version: '0.1.106'
appVersion: '0.1.106'
dependencies:
  - name: operator
    repository: file://../operator
    version: '2.2.6'
    condition: operator.enabled
  - name: bot
    repository: file://../bot
    version: '1.0.3'
    condition: bot.enabled
