---
# eevee Helm values

# Values for operator chart
operator:
  # Enable the operator chart
  enabled: true

# Values for bot chart
bot:
  # Name of this bot
  name: eevee-bot
  
  # IPC Configuration
  ipcConfig:
    # Name of the IPC config resource
    name: eevee-bot
  
    spec:
      # NATS configuration
      nats:
        # Managed NATS deployment configuration
        managed:
          # Should the eevee-operator deploy a NATS server for us?
          enabled: true
  
          # NATS container image to use
          image: docker.io/nats:latest
  
        # NATS token authentication configuration
        token:
          # Should the eevee-operator generate a token for NATS auth?
          generate: true
          # Secret reference
          secretKeyRef:
            secret:
              name: nats-auth-secret
            key: token
  
  # Router configuration
  router:
    # Enable router deployment
    enabled: true
  
    # Router spec
    spec:
      # Number of toolbox instances to deploy
      size: 1
  
      # Container image to use
      image: ghcr.io/eeveebot/router:latest
  
      # Image pull policy
      pullPolicy: Always
  
      # Enable metrics
      metrics: true
  
      # Metrics port
      metricsPort: 8080
  
      # IPC configuration name
      ipcConfig: eevee-bot
  
      # Router configuration
      moduleConfig: {}
  
  # Toolbox configuration
  toolbox:
    # Enable toolbox deployment
    enabled: true
  
    # Toolbox spec
    spec:
      # Number of toolbox instances to deploy
      size: 1
  
      # Container image to use
      image: ghcr.io/eeveebot/cli:latest
  
      # Image pull policy
      pullPolicy: Always
  
      # Enable metrics
      metrics: true
  
      # Metrics port
      metricsPort: 8080
  
      # IPC configuration name
      ipcConfig: eevee-bot

  # Bot Modules
  botModules:
  - name: irc-connector
    spec:
      # Number of module instances to deploy
      size: 1

      # Container image to use
      image: ghcr.io/eeveebot/connector-irc:latest

      # Image pull policy
      pullPolicy: Always

      # Enable metrics
      metrics: true

      # Metrics port
      metricsPort: 8080

      # IPC configuration name
      ipcConfig: eevee-bot

      # Module name - this identifies it as an IRC connector
      moduleName: irc

      # IRC configuration
      moduleConfig:
        # List of IRC connections
        connections:
        # Display name for this network (no . or * or > allowed)
        - name: my-irc-localhost

          # Enable this connection
          enabled: true

          # IRC connection configuration
          irc:
            host: localhost
            port: 6667
            ssl: true
            autoReconnect: true
            autoReconnectWait: 5000
            autoReconnectMaxRetries: 10
            autoRejoin: true
            autoRejoinWait: 5000
            autoRejoinMaxRetries: 5
            pingInterval: 30
            pingTimeout: 120

          # IRC Ident information
          ident:
            nick: eevee
            username: eevee
            gecos: eevee.bot
            version: "0.4.20"
            quitMsg: "eevee 0.4.20"

          # Actions to take after connecting
          postConnect:
          - # Join channels after connecting
            action: join
            join:
            - channel: '#eevee'

          # Send broadcast events for all received messages
          broadcastMessages: true
          # Settings related to command modules
          commands:
            # Common prefix regex to add to registered command regexes
            commonPrefixRegex: "^-"

  - name: router
    spec:
      # Number of module instances to deploy
      size: 1
  
      # Container image to use
      image: ghcr.io/eeveebot/router:latest
  
      # Image pull policy
      pullPolicy: Always
  
      # Enable metrics
      metrics: true
  
      # Metrics port
      metricsPort: 8080
  
      # IPC configuration name
      ipcConfig: eevee-bot
  
      # Module name - this identifies it as a router
      moduleName: router
  
      # Router configuration
      moduleConfig: {}

  - name: admin
    spec:
      # Number of module instances to deploy
      size: 1

      # Container image to use
      image: ghcr.io/eeveebot/admin:latest

      # Image pull policy
      pullPolicy: Always

      # Enable metrics
      metrics: false

      # Metrics port
      metricsPort: 8080

      # IPC configuration name
      ipcConfig: eevee-bot

      # Module name
      moduleName: admin

      moduleConfig:
        admins:
          - displayName: "root"
            # Unique identifier for this admin
            uuid: "8f4ddc7a-cd4c-4884-a981-944507ca3eba"
            # Platforms this admin is accepted on (regex patterns)
            acceptedPlatforms:
              - ".*"
            # Authentication methods for this admin
            authentication:
              # Currently supporting IRC hostmask identification
              irc:
                hostmask: "nick!username@example.com"

  - name: echo
    spec:
      # Number of module instances to deploy
      size: 1
  
      # Container image to use
      image: ghcr.io/eeveebot/echo:latest
  
      # Image pull policy
      pullPolicy: Always
  
      # Enable metrics
      metrics: false
  
      # Metrics port
      metricsPort: 8080
  
      # IPC configuration name
      ipcConfig: eevee-bot
  
      # Module name
      moduleName: echo
