---
# eevee Helm values

# Values for operator chart
operator:
  # Enable the operator chart
  enabled: true

# Values for bot chart
bot:
  # Enable the bot chart
  enabled: true

  ipcConfig:
    name: eevee-bot
    spec:
      nats:
        managed:
          enabled: true
          image: docker.io/nats:latest
        token:
          generate: true
          # Secret reference
          secretKeyRef:
            name: nats-auth-secret
            key: token

  toolbox:
    enabled: true
    spec:
      size: 1
      image: ghcr.io/eeveebot/cli:latest
      pullPolicy: Always
      metrics: true
      metricsPort: 8080
      ipcConfig: eevee-bot

  chatConnectionIrc:
    enabled: true
    spec:
      ipcConfig: eevee-bot
      image: ghcr.io/eeveebot/connector-irc:latest
      metrics: true
      metricsPort: 8080
      connections:
      - name: localhost
        enabled: true
        irc:
          host: localhost
          port: 6667
          ssl: true
          autoReconnect: true
          autoReconnectWait: 5000
          autoReconnectMaxRetries: 10
          autoRejoin: true
          autoRejoinWait: 5000
          autoRejoinMaxRetries: 5
          pingInterval: 30
          pingTimeout: 120
        ident:
          nick: eevee
          username: eevee
          gecos: eevee.bot
          version: "0.4.20"
          quitMsg: "eevee 0.4.20"
        postConnect:
        - action: join
          join:
          - channel: '#eevee'
