apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eevee-crd-job-role
  labels:
  {{- include "crds.labels" . | nindent 4 }}
rules:
- apiGroups:
  - eevee.bot
  resources:
  - chatconnectionirc
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - eevee.bot
  resources:
  - ipcconfig
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - eevee.bot
  resources:
  - toolbox
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eevee-crd-job-cluster-role
  labels:
  {{- include "crds.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resourceNames: []
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crds.serviceAccountName" . }}
  labels:
  {{- include "crds.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crd-job-role-binding
  labels:
  {{- include "crds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eevee-crd-job-role
subjects:
- kind: ServiceAccount
  name: '{{ include "crds.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-job-cluster-role-binding
  labels:
  {{- include "crds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eevee-crd-job-cluster-role
subjects:
- kind: ServiceAccount
  name: '{{ include "crds.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: eevee-crd-job
  labels:
    eevee.bot/crds: "true"
  {{- include "crds.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: eevee-crd-job-c8bcfaae
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: KUBE_IN_CLUSTER_CONFIG
          value: {{ quote .Values.eeveeCrdJob.main.env.kubeInClusterConfig }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.eeveeCrdJob.main.image.repository }}:{{ .Values.eeveeCrdJob.main.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.eeveeCrdJob.main.imagePullPolicy }}
        name: main
        resources: {{- toYaml .Values.eeveeCrdJob.main.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.eeveeCrdJob.main.containerSecurityContext
          | nindent 10 }}
      dnsPolicy: ClusterFirst
      nodeSelector: {{- toYaml .Values.eeveeCrdJob.nodeSelector | nindent 8 }}
      restartPolicy: Never
      securityContext: {{- toYaml .Values.eeveeCrdJob.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "crds.serviceAccountName" . }}
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      tolerations: {{- toYaml .Values.eeveeCrdJob.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.eeveeCrdJob.topologySpreadConstraints
        | nindent 8 }}
  ttlSecondsAfterFinished: 600
