eeveeOperatorService:
  ports:
  - port: 9000
    targetPort: 9000
  type: ClusterIP
kubernetesClusterDomain: cluster.local
operator:
  nodeSelector: {}
  operator:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    env:
      httpApiPort: "9000"
      kubeInClusterConfig: "true"
      logLevel: debug
      watchOtherNamespaces: "false"
    image:
      repository: ghcr.io/eeveebot/operator
      tag: 2.2.4
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 1500m
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 512Mi
  podSecurityContext:
    fsGroupChangePolicy: Always
    runAsNonRoot: true
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  tolerations: []
  topologySpreadConstraints: []
operatorApiToken:
  token: ""
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""
