# Ganked most of this from https://github.com/giantswarm/eevee-operator-app/blob/a8315a8e89dc291f70f8c5fbc800598ae347835f/helm/prometheus-operator-app/templates/crd-install/crd-rbac.yaml
# Consider their license to apply to this file in particular

{{- if .Values.crds.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eevee-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-1"
    {{- include "eevee-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
    {{- include "eevee-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "eevee-operator.CRDInstallSelector" . | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
        {{- include "eevee-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eevee-operator.crdInstall" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kubectl
        image: "docker.io/alpine:3.22"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          apk add --no-cache kubectl

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.

          kubectl apply -f /data/ 2>&1
        volumeMounts:
{{- range $path, $_ := .Files.Glob "crds/**" }}
        - name: {{ $path | base | trimSuffix ".yaml" | replace "_" "-" | replace "." "-"  }}
          mountPath: /data/{{ $path | base }}
          subPath: {{ $path | base }}
{{- end }}
        resources: {{- toYaml .Values.crds.resources | nindent 10 }}
      volumes:
{{ $currentScope := . }}
{{- range $path, $_ := .Files.Glob "crds/**" }}
    {{- with $currentScope }}
      - name: {{ $path | base | trimSuffix ".yaml" | replace "_" "-" | replace "." "-"  }}
        configMap:
          name: {{ include "eevee-operator.crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" | replace "_" "-" | replace "." "-" }}
          items:
          - key: content
            path: {{ $path | base }}
{{- end }}
{{- end }}
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eevee-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "eevee-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
    {{- include "eevee-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "eevee-operator.CRDInstallSelector" . | quote }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eevee-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "eevee-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
    {{- include "eevee-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "eevee-operator.CRDInstallSelector" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "eevee-operator.crdInstall" . }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eevee-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "eevee-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
    {{- include "eevee-operator.labels" . | nindent 4 }}
    role: {{ include "eevee-operator.CRDInstallSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eevee-operator.crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eevee-operator.crdInstall" . }}
    namespace: {{ .Release.Namespace | quote }}

---
{{/*
We have to create individual configmaps for each CRD - they exceed the total
allowed length for a configmap if they are combined.
*/}}
{{ $currentScope := . }}
  {{- range $path, $_ := .Files.Glob "crds/**" }}
    {{- with $currentScope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eevee-operator.crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" | replace "_" "-" | replace "." "-" }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "eevee-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
    {{- include "eevee-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "eevee-operator.CRDInstallSelector" . | quote }}
data:
  content: |
{{ .Files.Get $path | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
