{{- if .Values.crds.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eevee-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-1"
    {{- include "eevee-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
    {{- include "eevee-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "eevee-operator.CRDInstallSelector" . | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
        {{- include "eevee-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eevee-operator.crdInstall" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kubectl
        image: "docker.io/alpine:3.22"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          apk add --no-cache kubectl

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.

          kubectl apply -f /data/ 2>&1
        volumeMounts:
{{- range $path, $_ := .Files.Glob "crds/**" }}
        - name: {{ $path | base | trimSuffix ".yaml" }}
          mountPath: /data/{{ $path | base }}
          subPath: {{ $path | base }}
{{- end }}
        resources: {{- toYaml .Values.crds.resources | nindent 10 }}
      volumes:
{{ $currentScope := . }}
{{- range $path, $_ := .Files.Glob "crds/**" }}
    {{- with $currentScope }}
      - name: {{ $path | base | trimSuffix ".yaml" }}
        configMap:
          name: {{ include "eevee-operator.crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" }}
          items:
          - key: content
            path: {{ $path | base }}
{{- end }}
{{- end }}
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eevee-operator.crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "eevee-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "eevee-operator.crdInstall" . | quote }}
    {{- include "eevee-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "eevee-operator.CRDInstallSelector" . | quote }}

{{- end }}
