{{- range .Values.botModules }}
---
apiVersion: eevee.bot/v1
kind: botmodule
metadata:
  name: {{ .name }}
  namespace: {{ include "eevee-bot.botNamespace" $ }}
  labels:
    {{- include "eevee-bot.labels" $ | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
